# Generated by Django 4.1.7 on 2023-03-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pet_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='pet_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allowed pets?', verbose_name='Pets Allowed?'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(help_text='Positive numbers only', verbose_name='Price'),
        ),
    ]
