# Generated by Django 4.1.7 on 2023-03-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_last_modified_alter_house_pet_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='last_modified',
        ),
    ]
