# Generated by Django 4.1.7 on 2023-03-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participation",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
